### ISSUE TITLE
Code problem

### ISSUE THREAD

**Issue by Panamera2333** [georgeguo-cn/LGMRec#1]
After running your code, the results I get are slightly different from those in your paper, could you share the training log

**Comment by georgeguo-cn** [comment]
I have shared the training log in the dir `/log` before. Please take a look.

**Comment by xnjqhofhjgd** [comment]
After running your code, the error cannot reshape array of size 21626864 into shape (7050,4096)

**Comment by georgeguo-cn** [comment]
I reran the code and did not encounter the error message you mentioned. Can you provide the positioning of the error in the code?

**Comment by xnjqhofhjgd** [comment]
哥哥，咱俩加个微信吧，这个代码我怎么运行都有问题，可能有有些问题想问您，但是我不经常看我的邮箱



---Original---
From: "Zhiqiang ***@***.***&gt;
Date: Mon, Aug 19, 2024 19:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [georgeguo-cn/LGMRec] Code problem (Issue #1)




 
I reran the code and did not encounter the error message you mentioned. Can you provide the positioning of the error in the code?

**Comment by xnjqhofhjgd** [comment]
25 Aug 14:16&nbsp; &nbsp; INFO =========1/1: Parameters:['seed']=(999,)=======
models.lgmrec
Traceback (most recent call last):
&nbsp; File "main.py", line 20, in <module&gt;
&nbsp; &nbsp; quick_start(model=args.model, dataset=args.dataset, config_dict=config_dict, save_model=True)
&nbsp; File "/home/featurize/LGMRec/utils/quick_start.py", line 69, in quick_start
&nbsp; &nbsp; model = get_model(config['model'])(config, train_data).to(config['device'])
&nbsp; File "/home/featurize/LGMRec/models/lgmrec.py", line 12, in __init__
&nbsp; &nbsp; super(LGMRec, self).__init__(config, dataset)
&nbsp; File "/home/featurize/LGMRec/common/abstract_recommender.py", line 95, in __init__
&nbsp; &nbsp; self.v_feat = torch.from_numpy(np.load(v_feat_file_path, allow_pickle=True)).type(torch.FloatTensor).to(
&nbsp; File "/environment/miniconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 440, in load
&nbsp; &nbsp; pickle_kwargs=pickle_kwargs)
&nbsp; File "/environment/miniconda3/lib/python3.7/site-packages/numpy/lib/format.py", line 771, in read_array
&nbsp; &nbsp; array.shape = shape
ValueError: cannot reshape array of size 2621424 into shape (7050,4096)


---Original---
From: "Zhiqiang ***@***.***&gt;
Date: Mon, Aug 19, 2024 19:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [georgeguo-cn/LGMRec] Code problem (Issue #1)




 
I reran the code and did not encounter the error message you mentioned. Can you provide the positioning of the error in the code?

**Comment by xnjqhofhjgd** [comment]
解决完之后的报错:
25 Aug 14:21    INFO =========1/1: Parameters:['seed']=(999,)=======
models.lgmrec
Traceback (most recent call last):
&nbsp; File "main.py", line 20, in <module&gt;
&nbsp; &nbsp; quick_start(model=args.model, dataset=args.dataset, config_dict=config_dict, save_model=True)
&nbsp; File "/home/featurize/LGMRec/utils/quick_start.py", line 69, in quick_start
&nbsp; &nbsp; model = get_model(config['model'])(config, train_data).to(config['device'])
&nbsp; File "/home/featurize/LGMRec/models/lgmrec.py", line 43, in __init__
&nbsp; &nbsp; self.drop = nn.Dropout(p=1-self.keep_rate)
TypeError: unsupported operand type(s) for -: 'int' and 'list'
[ ]:
​25 Aug 14:21    INFO =========1/1: Parameters:['seed']=(999,)=======
models.lgmrec
Traceback (most recent call last):
&nbsp; File "main.py", line 20, in <module&gt;
&nbsp; &nbsp; quick_start(model=args.model, dataset=args.dataset, config_dict=config_dict, save_model=True)
&nbsp; File "/home/featurize/LGMRec/utils/quick_start.py", line 69, in quick_start
&nbsp; &nbsp; model = get_model(config['model'])(config, train_data).to(config['device'])
&nbsp; File "/home/featurize/LGMRec/models/lgmrec.py", line 43, in __init__
&nbsp; &nbsp; self.drop = nn.Dropout(p=1-self.keep_rate)
TypeError: unsupported operand type(s) for -: 'int' and 'list'
[ ]:
​
25 Aug 14:21    INFO =========1/1: Parameters:['seed']=(999,)=======
models.lgmrec
Traceback (most recent call last):
&nbsp; File "main.py", line 20, in <module&gt;
&nbsp; &nbsp; quick_start(model=args.model, dataset=args.dataset, config_dict=config_dict, save_model=True)
&nbsp; File "/home/featurize/LGMRec/utils/quick_start.py", line 69, in quick_start
&nbsp; &nbsp; model = get_model(config['model'])(config, train_data).to(config['device'])
&nbsp; File "/home/featurize/LGMRec/models/lgmrec.py", line 43, in __init__
&nbsp; &nbsp; self.drop = nn.Dropout(p=1-self.keep_rate)
TypeError: unsupported operand type(s) for -: 'int' and 'list'

---Original---
From: "Zhiqiang ***@***.***&gt;
Date: Mon, Aug 19, 2024 19:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [georgeguo-cn/LGMRec] Code problem (Issue #1)




 
I reran the code and did not encounter the error message you mentioned. Can you provide the positioning of the error in the code?

**Comment by zhangbinbinya** [comment]
1、ValueError: cannot reshape array of size 2621424 into shape (7050,4096)
2、TypeError: unsupported operand type(s) for -: 'int' and 'list'
Hello, I also encountered these two problems, may I ask if you have solved them? Can you answer how to solve them？

**Comment by Gs0098** [comment]
> 1、ValueError: cannot reshape array of size 2621424 into shape (7050,4096)1、值错误：无法将大小为 2621424 的数组重塑为形状(7050,4096) 2、TypeError: unsupported operand type(s) for -: 'int' and 'list'2、类型错误：不支持的操作类型 - 'int' 和 'list' Hello, I also encountered these two problems, may I ask if you have solved them? Can you answer how to solve them？你好，我也遇到了这两个问题，请问您解决了吗？能回答一下如何解决吗？

请问解决了吗

**Comment by xnjqhofhjgd** [comment]
没有解决



---Original---
From: ***@***.***&gt;
Date: Sat, Apr 12, 2025 19:16 PM
To: ***@***.***&gt;;
Cc: "Song ***@***.******@***.***&gt;;
Subject: Re: [georgeguo-cn/LGMRec] Code problem (Issue #1)


    
1、ValueError: cannot reshape array of size 2621424 into shape (7050,4096)1、值错误：无法将大小为 2621424 的数组重塑为形状(7050,4096) 2、TypeError: unsupported operand type(s) for -: 'int' and 'list'2、类型错误：不支持的操作类型 - 'int' 和 'list' Hello, I also encountered these two problems, may I ask if you have solved them? Can you answer how to solve them？你好，我也遇到了这两个问题，请问您解决了吗？能回答一下如何解决吗？
  
请问解决了吗

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  sjc-dd left a comment (georgeguo-cn/LGMRec#1)
  
1、ValueError: cannot reshape array of size 2621424 into shape (7050,4096)1、值错误：无法将大小为 2621424 的数组重塑为形状(7050,4096) 2、TypeError: unsupported operand type(s) for -: 'int' and 'list'2、类型错误：不支持的操作类型 - 'int' 和 'list' Hello, I also encountered these two problems, may I ask if you have solved them? Can you answer how to solve them？你好，我也遇到了这两个问题，请问您解决了吗？能回答一下如何解决吗？
  
请问解决了吗

**Comment by MrShouxingMa** [comment]
@xnjqhofhjgd @fahai-dd @zhangbinbinya 不知道你们解决没有，可能的解决方案如下：
第一个问题有可能是你数据文件没有加载对，按要求重新下载完整的数据就不会出现这个问题了
第二个问题可能是作者上传时的疏忽，混淆的命名；只需要把目录下“”configs/model“这个文件”LGMREC.yaml“改为”LGMRec.yaml”就好了，因为没完全加载所以才会报第二个错

**Comment by xnjqhofhjgd** [comment]
thank you



---Original---
From: ***@***.***&gt;
Date: Mon, Jun 15, 2026 07:51 AM
To: ***@***.***&gt;;
Cc: "Song ***@***.******@***.***&gt;;
Subject: Re: [georgeguo-cn/LGMRec] Code problem (Issue #1)


MrShouxingMa left a comment (georgeguo-cn/LGMRec#1)
 
@xnjqhofhjgd @fahai-dd @zhangbinbinya 不知道你们解决没有，可能的解决方案如下：
 第一个问题有可能是你数据文件没有加载对，按要求重新下载完整的数据就不会出现这个问题了
 第二个问题可能是作者上传时的疏忽，混淆的命名；只需要把目录下“”configs/model“这个文件”LGMREC.yaml“改为”LGMRec.yaml”就好了，因为没完全加载所以才会报第二个错
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications, keep track of coding agent tasks and review pull requests on the go with GitHub Mobile for iOS and Android. Download it today!
